### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by frenziek** [spassa/spassa.github.io#1]
- [ ] responsiveness
    - [ ] shrinkage
    - [ ] menu to hamburger
- [x] lorem imsum on profile, fix styling
- [ ] image gallery near gay kid
- [x] get rid of white bars
- [x] fix firefox scrolling
- [ ] experience responsiveness
- [ ] fix flexbox on gallery
- [ ] center titles on gallery boxes
- [ ] shading on gallery boxes away
- [ ] clean up contact section
